/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChangeTheme: typeof import('./../components/changeTheme.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions'];
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTabPane: typeof import('element-plus/es')['ElTabPane'];
    ElTabs: typeof import('element-plus/es')['ElTabs'];
    Prompt: typeof import('./../components/prompt.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SelectInput: typeof import('./../components/selectInput.vue')['default'];
    TextInput: typeof import('./../components/textInput.vue')['default'];
    V: typeof import('./../components/v.vue')['default'];
  }
}
